import React from 'react'

export default React.createContext({
    schoolLocation: "NONE",
    submissionEmail: "",
    submitterName: "",
    studentFirstName: "",
    studentLastName: "",
    garde: "",
    iepManager: "",
    involvedPeople: "",
    director: "",
    mars: "",
    contributingVariables: "",
    antecedent: "",
    disability: "",
    federal: "",
    age: "",
    raceEthnicity: "",
    gender: "",
    date: "",
    physicalHolding: "",
    seclusion: "",
    force: "",
    startTime: "",
    endTime: "",
    length: "",
    injury: "",
    lawEnforcment: "",
    program: "",
    roomlocation: "",
    disruption: "",
    emailHandler:  () => {},
    submitterNameHandler:  () => {},
    studentFirstNameHandler:  () => {},
    studentLastNameHandler:  () => {},
    studentGradeHandler:  () => {},
    iepManagerHandler:  () => {},
    involvedPeopleHandler:  () => {},
    directorHandler:  () => {},
    marsHandler:  () => {},
    contributingVariablesHandler:  () => {},
    antecedentHandler:  () => {},
    disabilityHandler:  () => {},
    federalHandler:  () => {},
    ageHandler:  () => {},
    raceEthnicityHandler:  () => {},
    genderHandler:  () => {},
    dateHandler:  () => {},
    physicalHoldingHandler:  () => {},
    seclusionHandler:  () => {},
    forceHandler:  () => {},
    startTimeHandler:  () => {},
    endTimeHandler:  () => {},
    lengthHandler:  () => {},
    injuryHandler:  () => {},
    lawEnforcmentHandler:  () => {},
    programHandler:  () => {},
    roomlocationHandler:  () => {},
    disruptionHandler:  () => {},
    handleSubmit: () => {}
})