import React from 'react';

export default React.createContext({
	school: 'NONE',
	submissionEmail: 'test',
	submitterName: '',
	studentLastName: '',
	involvedPeople: [],
	marss: '',
	people_involved: '',
	contributing_variables: '',
	antecedent: '',
	date: '',
	holds_used: '---',
	seclusion: '---',
	reasonable_force: '---',
	start_time: '',
	stop_time: '',
	duration: '',
	law_enforcment: '---',
	room_location: '---',
	major_disruption: '---',
	day_of_the_week: '---',
	student_injury: '---',
	staff_injury: '---',
	multiple_holds: '',
	dateHandler: () => {},
	timeHandler: () => {},
	Select: () => {},
	studentCheck: () => {},
	day_of_the_weekHandler: () => {},
	addHold: () => {},
	boolConversion: () => {},
	stateUpdate: () => {},
});
